name = "Meldworks"
author = "Deveyus"
version = "0.0.0-a5d0f44"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a27897022000669d46ffdce4e73dda3319e8b3b2bae5647fc8a9263a3c0b3f19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.74"

[options]
acceptable-game-versions = ["1.21.1"]
