name = "Meldworks"
author = "Deveyus"
version = "0.0.0-4dbfb6a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84cfae9d5ccfd38158b6b1176c27d183b375f5b479e75de68bf3608e54f363e9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21.1"]
