name = "Meldworks"
author = "Deveyus"
version = "0.0.0-c61b0d9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afa55967552a5aa62671c05f4a63a3936c8963dcbe1d59e4e607cacca364dd0c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4", "1.21.5"]
